services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_USER=mnist_app
      - POSTGRES_DB=digit_predictions
    restart: always

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - ./model:/app
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./web:/app
    depends_on:
      - model
      - db
    environment:
      - MODEL_URL=http://model:5000
      - DB_HOST=db
      - DB_USER=mnist_app
      - DB_PASSWORD=secure_password
      - DB_NAME=digit_predictions
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: always

volumes:
  postgres_data:
