services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      PYTHONUNBUFFERED: 1
      FLASK_DEBUG: 0  # Turn off debug for production
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8501}:8501"
    depends_on:
      - model
      - db
    environment:
      MODEL_URL: http://model:5000
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PYTHONUNBUFFERED: 1
      STREAMLIT_SERVER_ENABLE_CORS: "false"
    restart: always

volumes:
  postgres_data: