[theme]
primaryColor = "#4361ee"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#0b132b"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true 